//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace day5assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentinformation
    {
        public int Rollno { get; set; }
        public string name { get; set; }
        public System.DateTime dob { get; set; }
        public string gender { get; set; }
        public string department { get; set; }
        public string course { get; set; }
        public string semester { get; set; }
        public string saddress { get; set; }
        public int phonenumber { get; set; }
    }
}
